[target.x86_64-unknown-linux-gnu]
linker = "/opt/homebrew/bin/x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "/opt/homebrew/bin/aarch64-linux-gnu-gcc"

[env]
GITHUB_RAW_URL = "https://raw.githubusercontent.com/dcmd-org"
GITHUB_URL = "https://github.com/dcmd-org"
WEBSITE_URL = "https://dcmd.io"
DNS_IMAGE = "public.ecr.aws/dcmd/dns:latest"
TOOLBOX_IMAGE = "public.ecr.aws/dcmd/toolbox:latest"
PROXY_IMAGE = "public.ecr.aws/dcmd/proxy:latest"